global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: DEBUG
api:
   dashboard: true
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
certificatesResolvers:
  cloudflare:
    acme:
      email: whoiamrootuser@proton.me
      storage: /var/traefik/certs/cloudflare-acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
providers:
  docker:
    exposedByDefault: false
    network: frontend
  file:
    directory: /etc/traefik
    watch: true
  http:
    endpoint: "http://mantrae:3000/api/default"
    headers:
        Authorization: Basic YWRtaW46Y2YwZmIwNmQ4MDQ1MTc3ODNjYjBlZDBkYjY0MzAyNTE5NWI4

http:
  routers:
    dashboard:
      rule: "Host(`traefik.testespace.com.br`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      service: api@internal
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
