---
services:
  traefik:
    image: traefik:v3.1.5
    container_name: traefik
    command:
      - --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/run/docker.sock:ro
      - ./config/:/etc/traefik/:ro
      - ./certs/:/var/traefik/certs/:rw
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - OWNER_EMAIL=${OWNER_EMAIL}
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    external: false  # <-- (Optional) Change this to false if you want to create a new network
