---
services:
  traefik:
    image: traefik:v3.1.5
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/run/docker.sock:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./certs/:/var/traefik/certs/:rw
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - OWNER_EMAIL=${OWNER_EMAIL}
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    external: true  # <-- (Optional) Change this to false if you want to create a new network
